import { Release } from "models/release.model";

export const data: Array<Release> = [
  {
    id: 11334732,
    status: "Accepted",
    type: "release",
    format: '12"',
    label: "Stockholm LTD",
    title: "Aftermath",
    resource_url: "https://api.discogs.com/releases/11334732",
    role: "Main",
    artist: "The Persuader & Nima Khak",
    year: 2017,
    thumb: "",
    stats: { community: { in_wantlist: 40, in_collection: 47 } },
  },
  {
    id: 12855756,
    status: "Accepted",
    type: "release",
    format: "3xFile, MP3, EP",
    label: "Strange Idols",
    title: "The Kosmos EP",
    resource_url: "https://api.discogs.com/releases/12855756",
    role: "Main",
    artist: "The Persuader",
    year: 2017,
    thumb: "",
    stats: { community: { in_wantlist: 4, in_collection: 4 } },
  },
  {
    id: 13392912,
    status: "Accepted",
    type: "release",
    format: '12", EP, Ltd',
    label: "Kalvaberget Records",
    title: "Cosmic Isolation EP",
    resource_url: "https://api.discogs.com/releases/13392912",
    role: "Main",
    artist: "AD* & The Persuader",
    year: 2019,
    thumb: "",
    stats: { community: { in_wantlist: 44, in_collection: 79 } },
  },
  {
    id: 1157881,
    title: "Loves You All Night And Day",
    type: "master",
    main_release: 88892,
    artist: "Superlova",
    role: "Remix",
    resource_url: "https://api.discogs.com/masters/1157881",
    year: 1997,
    thumb: "",
    stats: { community: { in_wantlist: 527, in_collection: 173 } },
  },
  {
    id: 169563,
    title: "The Big Bang Theory",
    type: "master",
    main_release: 119,
    artist: "Dr. Nobody",
    role: "Remix",
    resource_url: "https://api.discogs.com/masters/169563",
    year: 1997,
    thumb: "",
    stats: { community: { in_wantlist: 257, in_collection: 374 } },
  },
  {
    id: 5955,
    status: "Accepted",
    type: "release",
    format: "CD, Comp",
    label: "Svek",
    title: "The Lords Of Svek Vol. 4",
    resource_url: "https://api.discogs.com/releases/5955",
    role: "Remix",
    artist: "Various",
    trackinfo: "Discophrenia (The Pers...",
    year: 1998,
    thumb: "",
    stats: { community: { in_wantlist: 121, in_collection: 185 } },
  },
  {
    id: 1042102,
    title: "Diskophrenia Remixes",
    type: "master",
    main_release: 15542,
    artist: "Ralph Lundsten",
    role: "Remix",
    resource_url: "https://api.discogs.com/masters/1042102",
    year: 1998,
    thumb: "",
    stats: { community: { in_wantlist: 227, in_collection: 330 } },
  },
  {
    id: 229135,
    status: "Accepted",
    type: "release",
    format: "2xCD, Comp, Mixed",
    label: "Kaos Records",
    title: "Chill On Kaos Volume Two",
    resource_url: "https://api.discogs.com/releases/229135",
    role: "Remix",
    artist: "Various",
    trackinfo: "Diskophrenia (The Pers...",
    year: 2001,
    thumb: "",
    stats: { community: { in_wantlist: 13, in_collection: 17 } },
  },
  {
    id: 2629499,
    status: "Accepted",
    type: "release",
    format: "2xCDr, Comp, Promo",
    label: "Raw Elements",
    title: "Raw Essentials",
    resource_url: "https://api.discogs.com/releases/2629499",
    role: "Remix",
    artist: "Various",
    trackinfo: "All Night ( Stephan Gr...",
    year: 2008,
    thumb: "",
    stats: { community: { in_wantlist: 18, in_collection: 4 } },
  },
  {
    id: 2219613,
    status: "Accepted",
    type: "release",
    format: "CD, Mixed + CD, Mixed + CD, Mixed + CD, Mixed + Bo",
    label: "Live At Robert Johnson",
    title: "Volume 1-4 - Live At Robert Johnson",
    resource_url: "https://api.discogs.com/releases/2219613",
    role: "Remix",
    artist: "Various",
    trackinfo: "The Big Bang Theory (R...",
    year: 2010,
    thumb: "",
    stats: { community: { in_wantlist: 64, in_collection: 40 } },
  },
  {
    id: 944234,
    title: "Live At Robert Johnson",
    type: "master",
    main_release: 2116649,
    artist: "Thomas Hammann & Gerd Janson",
    role: "Remix",
    resource_url: "https://api.discogs.com/masters/944234",
    year: 2010,
    thumb: "",
    stats: { community: { in_wantlist: 54, in_collection: 92 } },
  },
  {
    id: 5468479,
    status: "Accepted",
    type: "release",
    format: '12"',
    label: "Spectral Sound",
    title: "My Busted SH-101",
    resource_url: "https://api.discogs.com/releases/5468479",
    role: "Remix",
    artist: "Alexi Delano",
    trackinfo: "My Busted SH-101 (The ...",
    year: 2014,
    thumb: "",
    stats: { community: { in_wantlist: 54, in_collection: 82 } },
  },
  {
    id: 5885934,
    status: "Accepted",
    type: "release",
    format: '12"',
    label: "Alexi Delano Limited",
    title: "Guitarra Trina",
    resource_url: "https://api.discogs.com/releases/5885934",
    role: "Remix",
    artist: "Damien K. Sahri*",
    trackinfo: "Guitarra Trina (The Pe...",
    year: 2014,
    thumb: "",
    stats: { community: { in_wantlist: 22, in_collection: 37 } },
  },
  {
    id: 6699352,
    status: "Accepted",
    type: "release",
    format: '12"',
    label: "Allofon Recordings",
    title: "Sopp\u00e5sar / 5 Months Later",
    resource_url: "https://api.discogs.com/releases/6699352",
    role: "Remix",
    artist: "Carl Hasselrot & Mattias Olsson (6) / Techjacka",
    trackinfo: "Sopp\u00e5sar (The Persuade..",
    year: 2015,
    thumb: "",
    stats: { community: { in_wantlist: 8, in_collection: 10 } },
  },
  {
    id: 6954733,
    status: "Accepted",
    type: "release",
    format: '12"',
    label: "Odd Even",
    title: "Diffused Light Vol. 1",
    resource_url: "https://api.discogs.com/releases/6954733",
    role: "Remix",
    artist: "Various",
    trackinfo: "Eden (The Persuader Re...",
    year: 2015,
    thumb: "",
    stats: { community: { in_wantlist: 45, in_collection: 82 } },
  },
  {
    id: 1723086,
    title: " Heart (Remixes)  ",
    type: "master",
    main_release: 7679347,
    artist: "Joel Alter",
    role: "Remix",
    resource_url: "https://api.discogs.com/masters/1723086",
    year: 2015,
    thumb: "",
    stats: { community: { in_wantlist: 90, in_collection: 125 } },
  },
  {
    id: 8321965,
    status: "Accepted",
    type: "release",
    format: '12"',
    label: "Constant Sound",
    title: "Capricorn Meets Leo",
    resource_url: "https://api.discogs.com/releases/8321965",
    role: "Remix",
    artist: "Vrsion",
    trackinfo: "Capricorn Meets Leo (T...",
    year: 2016,
    thumb: "",
    stats: { community: { in_wantlist: 32, in_collection: 59 } },
  },
  {
    id: 15490621,
    status: "Accepted",
    type: "release",
    format: "5xFile, WAV, Single",
    label: "Kompakt",
    title: "Welcome To The Present Remixe",
    resource_url: "https://api.discogs.com/releases/15490621",
    role: "Remix",
    artist: "Blond:ish",
    trackinfo: "Nada Brahma (The Persu...",
    year: 2016,
    thumb: "",
    stats: { community: { in_wantlist: 0, in_collection: 2 } },
  },
  {
    id: 1644222,
    title: "Consistency Remixes ",
    type: "master",
    main_release: 14466486,
    artist: "Ray Kajioka",
    role: "Remix",
    resource_url: "https://api.discogs.com/masters/1644222",
    year: 2016,
    thumb: "",
    stats: { community: { in_wantlist: 1, in_collection: 2 } },
  },
  {
    id: 10885504,
    status: "Accepted",
    type: "release",
    format: '12", EP',
    label: "Visionquest",
    title: "Water Colors EP",
    resource_url: "https://api.discogs.com/releases/10885504",
    role: "Remix",
    artist: "Alexi Delano",
    trackinfo: "Water Colors (The Pers...",
    year: 2017,
    thumb: "",
    stats: { community: { in_wantlist: 26, in_collection: 27 } },
  },
];
